pull_request_rules:
  - name: self-assign PRs
    conditions:
      - -merged
      - -closed
      - "#assignee=0"
    actions:
      assign:
        add_users:
          - "{{ author }}"
  - name: automatic merge when not WIP, CI passes, and at least 1 approving review
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=tests 3.10 / ubuntu-latest
      - check-success=pre-commit 3.10 / ubuntu-latest
      - check-success=docs-build 3.10 / ubuntu-latest
      - base=master
      - label!=work-in-progress
    actions:
      queue:
        method: squash
        name: default
queue_rules:
  - name: default
    conditions:
      - check-success=tests 3.10 / ubuntu-latest
      - check-success=pre-commit 3.10 / ubuntu-latest
      - check-success=docs-build 3.10 / ubuntu-latest
