providers:
  google_secretmanager_1:
    kind: google_secretmanager
    maps:
      - id: gsm
        path: projects/{{ get_env(name="GCP_PROJECT_ID", default="pyro-284215") }}
        keys:
          KUBECONFIG: ==
          CACHIX_AUTH_TOKEN: ==
          CLOUDFLARE_ACCOUNT_ID: ==
          CLOUDFLARE_API_TOKEN: ==
