# # # #
schema_version: 1

context:
  name: pyrovelocity
  version: 0.4.0b4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # source archive from PyPI for release to main label
  # source archive from git tag/ref/rev for testing/release to _dev label
  # url: https://github.com/{{ gitorg }}/{{ name }}/archive/refs/tags/{{ gittag }}.tar.gz
  # url: https://github.com/{{ gitorg }}/{{ name }}/archive/refs/heads/{{ gitref }}.tar.gz
  # url: https://github.com/{{ gitorg }}/{{ name }}/archive/{{ gitrev }}.tar.gz
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 5f905e8e35f621086dd475cbea2c62804119642eaff6402a67e2a179c947c51d
  # install from local directory
  # path: ../..

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - pyrovelocity=pyrovelocity.workflows.cli:main

requirements:
  host:
    - python >=3.11,<3.12
    - pip
    - poetry-core >=1.6.0,<2
  run:
    - python >=3.11,<3.12
    - adjusttext >=1.1.1
    - altair >=5.3.0
    - anndata >=0.10.5
    - anyio >=4.3.0
    - appdirs >=1.4.4
    - arviz >=0.17.1
    - astropy >=6.1.2
    - beartype >=0.18.5,<0.20.0
    - click >=8.1.7
    - colorlog >=6.7.0
    - daft >=0.1.2
    - dill >=0.3.8
    - diffrax >=0.5.0
    - diskcache >=5.6.1
    - duckdb >=1.0.0
    - einops >=0.7.0
    - expression >=5.0.2
    - flax >=0.8.1
    - fsspec >=2024.3.0
    - greenlet >=3.0.3
    - h5py >=3.9.0
    - httpx >=0.27.0
    - ibis-duckdb >=9.2.0
    # https://github.com/google/jax/issues/21116
    # https://github.com/google/jax/pull/21734
    # next update will need to be >=0.4.29
    - jax >=0.4.23,<0.4.27
    - jaxlib >=0.4.23,<0.4.27
    - jaxtyping >=0.2.25
    - leidenalg >=0.9.1
    - lightning >=2.0.0
    - matplotlib-base >=3.9.1
    - mlflow >=2.13.0
    - numpyro >=0.15.0
    - pandas >=2.0.0
    - plumbum >=1.8.2
    - polars >=0.20.17
    - pyarrow >=14.0.2
    - pyro-ppl >=1.9.1
    - pytorch >=2.1.2
    - pyyaml >=6.0.1
    - returns >=0.22.0
    - rich >=13.7.1
    - scanpy >=1.10.1
    - scipy >=1.10.1,<1.14.0
    - scvelo >=0.3.1,<0.3.3
    # this upper bound should be removed
    # when it is removed as a constraint
    # derived from
    # noarch/scvelo-0.3.2-pyhd8ed1ab_1.conda
    - scikit-learn <1.2.0
    - scvi-tools >=1.1.1,<1.2.0
    - seaborn >=0.13.2
    - sparse >=0.15.4
    - statsmodels >=0.14.2
    - sympy >=1.12
    - termcolor >=2.2.0
    - tiledb-py >=0.31.1
    - torchmetrics >=1.2.1
    - trio >=0.26.0
    - validators >=0.33.0
    - vegafusion >=1.6.9
    - vegafusion-python-embed >=1.6.9
    - vl-convert-python >=1.6.0
    - zstandard >=0.23.0
    # workflows
    - dataclasses-json >=0.5.7
    - dulwich >=0.21.7
    - flytekit >=1.13.3
    - google-api-python-client >=2.138.0
    - google-cloud-storage >=2.18.0
    - hydra-core >=1.3.2
    - hydra-zen >=0.13.0
    - ipywidgets >=8.1.3
    - jupytext >=1.16.3
    - mashumaro >=3.13.1
    - nbconvert >=7.16.4
    - nbformat >=5.10.4
    - omegaconf >=2.3.0
    - papermill >=2.6.0
    - pyperclip >=1.9.0
    - python-dotenv >=1.0.1
    - rich-click >=1.8.3

tests:
  - python:
      imports:
        - pyrovelocity
      pip_check: false
  - requirements:
      run:
        - hypothesis
        - pytest
        - pytest-cov
        - pytest-mock
        - requests-mock
        - xdoctest
    script:
      - |
        pytest \
        -rA \
        --xdoc \
        --no-cov \
        --disable-warnings \
        -k "not workflows and not transcriptome_properties" \
        --pyargs pyrovelocity

about:
  summary: Probabilistic modeling of RNA Velocity with pyro.
  license: AGPL-3.0-only
  license_file: LICENSE
  description: |
    Pyrovelocity is a library for probabilistic inference in minimal models approximating gene expression
    dynamics from multimodal single-cell sequencing data.

    - docs: [https://docs.pyrovelocity.net](https://docs.pyrovelocity.net)
    - source: [https://github.com/pinellolab/pyrovelocity](https://github.com/pinellolab/pyrovelocity)

    PyPI: [https://pypi.org/project/pyrovelocity](https://pypi.org/project/pyrovelocity)

  homepage: https://github.com/pinellolab/pyrovelocity
  repository: https://github.com/pinellolab/pyrovelocity
  documentation: https://docs.pyrovelocity.net

extra:
  recipe-maintainers:
    - cameronraysmith
    - qinqian
