name: pyrovelocity-gpu

# generate lock file:
#   conda-lock --conda mamba --log-level DEBUG -f environment-gpu.yml --lockfile conda-lock.yml
# see conda-lock.yml header for installation instructions:
#   conda-lock install -n YOURENV --file conda-lock.yml

channels:
  - conda-forge
  - bioconda
  # https://stackoverflow.com/a/71110028/446907
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults

dependencies:
  - python
  - leidenalg
  - pyro-ppl=1.8.3
  - pytorch-gpu=1.13.1
  - seaborn=0.11.2
  - anndata=0.8.0
  - scvelo=0.2.5
  - pandas=1.5.3
  - h5py
  - anndata
  - pip
  - scvi-tools
  - scikit-misc
  - torchmetrics
  - adjusttext
  - xdoctest
  - astropy
  - click
  - colorlog
  - omegaconf
  - rich
  - hydra-core
  - mlflow
  - termcolor
  - tqdm
  - ipywidgets
  - zstandard
  # dev
  - zsh
  - tree
  - htop
  - make
  - pytest
  - hypothesis
  - xdoctest
  - dvc
  - git
  - gh
  - pip:
      - hydra-zen==0.10.0
      - cospar==0.1.9

## Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
