# syntax=docker/dockerfile:1
FROM condaforge/mambaforge:23.1.0-1
LABEL maintainer="pyrovelocity team"

WORKDIR /pyrovelocity
COPY . .

RUN mamba init
RUN mamba env update -n base -f conda/environment-gpu.yml
RUN pip install --no-deps -e .
