#!/usr/bin/env bash

set -euxo pipefail

QUARTO_VERSION="1.6.4"
QUARTO_FILE="quarto-${QUARTO_VERSION}-linux-amd64.tar.gz"
QUARTO_URL="https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/${QUARTO_FILE}"
wget -nv ${QUARTO_URL}
tar zxf ${QUARTO_FILE} 

set +x
echo "$GOOGLE_APPLICATION_CREDENTIALS_DATA" > /tmp/sa.json
set -x
pipx install dvc[gs]
dvc pull --force --allow-missing --verbose

poetry install --with docs,workflows --sync
poetry run quartodoc build --verbose --config nbs/_quarto.yml
(cd nbs && poetry run quartodoc interlinks)
./quarto-${QUARTO_VERSION}/bin/quarto render nbs
