#!/usr/bin/env bash

set -euxo pipefail

QUARTO_VERSION="1.4.551"
QUARTO_FILE="quarto-${QUARTO_VERSION}-linux-amd64.tar.gz"
QUARTO_URL="https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/${QUARTO_FILE}"
wget ${QUARTO_URL}
tar zxf ${QUARTO_FILE} 

poetry install --with docs,workflows --sync
poetry run quartodoc build --verbose --config nbs/_quarto.yml
cd nbs && poetry run quartodoc interlinks
./quarto-${QUARTO_VERSION}/bin/quarto render nbs
