vars:
  - config.yaml

stages:
  data_download:
    cmd: python data_download.py --config=config.yaml
    deps:
      - data_download.py
    params:
      - config.yaml:
          - base
          - data_external.scvelo.pancreas
          - data_external.scvelo.pbmc68k
          - data_external.pyrovelocity.larry
    outs:
      - ${data_external.scvelo.pancreas.rel_path}:
          persist: true
      - ${data_external.scvelo.pbmc68k.rel_path}:
          persist: true
      - ${data_external.pyrovelocity.larry.rel_path}:
          persist: true

  preprocess:
    cmd: python preprocess.py --config=config.yaml
    deps:
      - preprocess.py
      - ${data_external.scvelo.pancreas.rel_path}
      - ${data_external.scvelo.pbmc68k.rel_path}
    params:
      - config.yaml:
          - base
          - data_external.scvelo.pancreas
          - data_external.scvelo.pbmc68k
    outs:
      - ${data_external.scvelo.pancreas.derived.rel_path}:
          persist: true
      - ${data_external.scvelo.pbmc68k.derived.rel_path}:
          persist: true

  train_pancreas_model1:
    cmd: python fig2/fig2_pancreas_train.py --config=config.yaml
    deps:
      - fig2/fig2_pancreas_train.py
      - ${data_external.scvelo.pancreas.derived.rel_path}
    params:
      - config.yaml:
          - model_training.pancreas_model1
    outs:
      - ${model_training.pancreas_model1.trained_data_path}:
          persist: true
      - ${model_training.pancreas_model1.model_path}:
          persist: true
      - ${model_training.pancreas_model1.pyrovelocity_data_path}:
          persist: true
