vars:
  - config.yaml

stages:
  data_download:
    foreach: ${data_sets}
    do:
      cmd: python data_download.py process_data=[${key}]
      deps:
        - data_download.py
      params:
        - config.yaml:
            - data_sets.${key}
      outs:
        - ${item.rel_path}:
            persist: true

  preprocess:
    foreach: ${data_sets}
    do:
      cmd: python preprocess.py process_data=[${key}]
      deps:
        - preprocess.py
        - ${item.rel_path}
      params:
        - config.yaml:
            - data_sets.${key}
      outs:
        - ${item.derived.rel_path}
        - ${item.derived.thresh_histogram_path}
        - ${item.derived.thresh_histogram_path}.png

  train:
    foreach: ${model_training}
    do:
      cmd: /usr/bin/time -v python train.py train_models=[${key}]
      deps:
        - train.py
        - ${item.input_data_path}
      params:
        - config.yaml:
            - base
            - model_training.${key}
      outs:
        - ${item.run_info_path}:
            cache: false
        - ${item.training_parameters.loss_plot_path}
        # - ${item.trained_data_path}
        - ${item.model_path}
        - ${item.posterior_samples_path}
        # - ${item.pyrovelocity_data_path}

  postprocess:
    foreach: ${model_training}
    do:
      cmd: /usr/bin/time -v python postprocess.py train_models=[${key}]
      deps:
        - postprocess.py
        - ${item.input_data_path}
        - ${item.model_path}
        - ${item.posterior_samples_path}
      params:
        - config.yaml:
            - base
            - model_training.${key}
      metrics:
        - ${item.metrics_path}:
            cache: false
      outs:
        - ${item.pyrovelocity_data_path}
        - ${item.trained_data_path}

  summarize:
    foreach: ${reports.model_summary}
    do:
      cmd: /usr/bin/time -v python summarize.py train_models=[${key}]
      deps:
        - summarize.py
        - ${item.trained_data_path}
        - ${item.pyrovelocity_data_path}
      params:
        - config.yaml:
            - base
            - reports.model_summary.${key}
      outs:
        - ${item.dataframe_path}
        - ${item.volcano_plot}
        - ${item.volcano_plot}.png
        - ${item.rainbow_plot}
        - ${item.rainbow_plot}.png
        - ${item.vector_field_plot}
        - ${item.vector_field_plot}.png
        - ${item.shared_time_plot}
        - ${item.fig2_part1_plot}
        - ${item.fig2_part1_plot}.png
        - ${item.fig2_part2_plot}
        - ${item.fig2_part2_plot}.png
        - ${item.violin_clusters_lin}
        - ${item.violin_clusters_lin}.png
        - ${item.violin_clusters_log}
        - ${item.violin_clusters_log}.png
        - ${item.uncertainty_param_plot}
        - ${item.uncertainty_param_plot}.png

  figureS2:
    cmd: python figS2/figure.py train_models=[pancreas_model2,pbmc10k_model2,pbmc68k_model2,pons_model2,larry_model2,larry_neu_model2,larry_mono_model2,larry_tips_model2]
    deps:
      - figS2/figure.py
      - ${model_training.pancreas_model2.pyrovelocity_data_path}
      - ${model_training.pbmc10k_model2.pyrovelocity_data_path}
      - ${model_training.pbmc68k_model2.pyrovelocity_data_path}
      - ${model_training.pons_model2.pyrovelocity_data_path}
      - ${model_training.larry_model2.pyrovelocity_data_path}
      - ${model_training.larry_neu_model2.pyrovelocity_data_path}
      - ${model_training.larry_mono_model2.pyrovelocity_data_path}
      - ${model_training.larry_multilineage_model2.pyrovelocity_data_path}
      - ${model_training.larry_tips_model2.pyrovelocity_data_path}
    params:
      - config.yaml:
          - reports.figureS2
    outs:
      - ${reports.figureS2.boxplot_other_lin}
      - ${reports.figureS2.boxplot_other_lin}.png

  figureS2_extras:
    cmd: python figS2/figure_extras.py train_models=[pbmc68k_model2]
    deps:
      - figS2/figure_extras.py
      - ${model_training.pbmc68k_model2.pyrovelocity_data_path}
    params:
      - config.yaml:
          - reports.figureS2_extras
    outs:
      - ${reports.figureS2_extras.subset_genes_plot}
      - ${reports.figureS2_extras.subset_genes_plot}.png

  figureS2_extra_2:
    cmd: python figS2/figure_extra_2.py train_models=[pancreas_model2,pbmc10k_model2,pbmc68k_model2,pons_model2,larry_model2,larry_neu_model2,larry_mono_model2,larry_multilineage_model2,larry_tips_model2]
    deps:
      - figS2/figure_extra_2.py
      - ${model_training.pancreas_model2.pyrovelocity_data_path}
      - ${model_training.pbmc10k_model2.pyrovelocity_data_path}
      - ${model_training.pbmc68k_model2.pyrovelocity_data_path}
      - ${model_training.pons_model2.pyrovelocity_data_path}
      - ${model_training.larry_model2.pyrovelocity_data_path}
      - ${model_training.larry_neu_model2.pyrovelocity_data_path}
      - ${model_training.larry_mono_model2.pyrovelocity_data_path}
      - ${model_training.larry_multilineage_model2.pyrovelocity_data_path}
      - ${model_training.larry_tips_model2.pyrovelocity_data_path}
    params:
      - config.yaml:
          - reports.figureS2_extra_2
    outs:
      - ${reports.figureS2_extra_2.mean_length_vs_uncertain}
      - ${reports.figureS2_extra_2.mean_length_vs_uncertain}.png

  # figureS3:
  #   cmd: python figS3/figure.py
  #   deps:
  #     - figS3/figure.py
  #     - ${model_training.pancreas_model2.trained_data_path}
  #     - ${model_training.pancreas_model2.pyrovelocity_data_path}
  #     - ${model_training.pbmc68k_model2.trained_data_path}
  #     - ${model_training.pbmc68k_model2.pyrovelocity_data_path}
  #   params:
  #     - config.yaml:
  #         - reports.figureS3
  #   outs:
  #     - ${reports.figureS3.tif_path}
  #     - ${reports.figureS3.svg_path}

  figureS3_extras:
    cmd: python figS3/figure_extras.py train_models=[pancreas_model2,pbmc10k_model2,pbmc68k_model2,pons_model2,larry_model2,larry_neu_model2,larry_mono_model2,larry_multilineage_model2,larry_tips_model2]
    deps:
      - figS3/figure_extras.py
      - ${model_training.pancreas_model2.pyrovelocity_data_path}
      - ${model_training.pbmc10k_model2.pyrovelocity_data_path}
      - ${model_training.pbmc68k_model2.pyrovelocity_data_path}
      - ${model_training.pons_model2.pyrovelocity_data_path}
      - ${model_training.larry_model2.pyrovelocity_data_path}
      - ${model_training.larry_neu_model2.pyrovelocity_data_path}
      - ${model_training.larry_mono_model2.pyrovelocity_data_path}
      - ${model_training.larry_multilineage_model2.pyrovelocity_data_path}
      - ${model_training.larry_tips_model2.pyrovelocity_data_path}
    params:
      - config.yaml:
          - reports.figureS3
    outs:
      - ${reports.figureS3_extras.violin_plots_pbmc_lin}
      - ${reports.figureS3_extras.violin_plots_pbmc_log}
      - ${reports.figureS3_extras.violin_plots_larry_lin}
      - ${reports.figureS3_extras.violin_plots_larry_log}

  figure3:
    cmd: python fig3/figure.py
    deps:
      - fig3/figure.py
      - ${model_training.larry_model2.trained_data_path}
      - ${model_training.larry_model2.pyrovelocity_data_path}
      - ${model_training.larry_mono_model2.trained_data_path}
      - ${model_training.larry_mono_model2.pyrovelocity_data_path}
      - ${model_training.larry_neu_model2.trained_data_path}
      - ${model_training.larry_neu_model2.pyrovelocity_data_path}
      - ${model_training.larry_multilineage_model2.trained_data_path}
      - ${model_training.larry_multilineage_model2.pyrovelocity_data_path}
    params:
      - config.yaml:
          - reports.figure3
    outs:
      - ${reports.figure3.figure3}
      - ${reports.figure3.figure3}.png

  figureS4:
    cmd: python figS4/figure.py
    deps:
      - figS4/figure.py
      - ${model_training.larry_model2.trained_data_path}
      - ${model_training.larry_model2.pyrovelocity_data_path}
      - ${model_training.larry_mono_model2.trained_data_path}
      - ${model_training.larry_mono_model2.pyrovelocity_data_path}
      - ${model_training.larry_neu_model2.trained_data_path}
      - ${model_training.larry_neu_model2.pyrovelocity_data_path}
      - ${model_training.larry_multilineage_model2.trained_data_path}
      - ${model_training.larry_multilineage_model2.pyrovelocity_data_path}
    params:
      - config.yaml:
          - reports.figureS4
    outs:
      - ${reports.figureS4.figureS4}
      - ${reports.figureS4.figureS4}.png

  # figure2:
  #   cmd: python fig2/figure.py
  #   deps:
  #     - fig2/figure.py
  #     - ${model_training.pancreas_model1.trained_data_path}
  #     - ${model_training.pancreas_model1.pyrovelocity_data_path}
  #     - ${model_training.pbmc68k_model1.trained_data_path}
  #     - ${model_training.pbmc68k_model1.pyrovelocity_data_path}
  #   params:
  #     - config.yaml:
  #         - reports.figure2
  #   outs:
  #     - ${reports.figure2.tif_path}
  #       # persist: true
  #     - ${reports.figure2.svg_path}
  #       # persist: true
  #     - ${reports.figure2.biomarker_selection_path}
  #     - ${reports.figure2.biomarker_phaseportrait_path}
  #     - ${reports.figure2.uncertainty_param_plot_path}

  # figure2_extras:
  #   cmd: python fig2/figure_extras.py reports.model_summary.summarize=[pbmc10k_model2,larry_tips_model2,pbmc68k_model2]
  #   deps:
  #     - fig2/figure_extras.py
  #     - ${model_training.pbmc10k_model2.pyrovelocity_data_path}
  #     - ${model_training.larry_tips_model2.pyrovelocity_data_path}
  #     - ${model_training.pbmc68k_model2.pyrovelocity_data_path}
  #   params:
  #     - config.yaml:
  #         - reports.figure2
  #   outs:
  #     - ${reports.figure2_extras.shared_time_plot}
