vars:
  - config.yaml

stages:
  ## Integrated data download stage introduces unnecessary dependence among downstream stages
  # data_download:
  #   cmd: python data_download.py
  #   deps:
  #     - data_download.py
  #   params:
  #     - config.yaml:
  #         - base
  #         - data_external.scvelo.pancreas
  #         - data_external.scvelo.pbmc68k
  #         - data_external.pyrovelocity.larry
  #   outs:
  #     - ${data_external.scvelo.pancreas.rel_path}:
  #         persist: true
  #     - ${data_external.scvelo.pbmc68k.rel_path}:
  #         persist: true
  #     - ${data_external.pyrovelocity.larry.rel_path}:
  #         persist: true

  ## foreach stage doesn't clearly support nesting variables in the output definition
  # data_download:
  #   foreach:
  #     - source: scvelo
  #       data: pancreas
  #     - source: scvelo
  #       data: pbmc68k
  #     - source: pyrovelocity
  #       data: larry
  #   do:
  #     cmd: python data_download.py data_external.sources=[${item.source}] data_external.scvelo.download=[${item.data}]
  #     deps:
  #       - data_download.py
  #     params:
  #       - config.yaml:
  #           - base
  #           - data_external.${item.source}.${item.data}
  #     outs:
  #       - ${data_external.${item.source}.${item.data}.rel_path}:
  #           persist: true

  data_download_pancreas:
    cmd: python data_download.py data_external.sources=[scvelo] data_external.scvelo.download=[pancreas]
    deps:
      - data_download.py
    params:
      - config.yaml:
          - base
          - data_external.scvelo.pancreas
    outs:
      - ${data_external.scvelo.pancreas.rel_path}:
          persist: true

  data_download_pbmc68k:
    cmd: python data_download.py data_external.sources=[scvelo] data_external.scvelo.download=[pbmc68k]
    deps:
      - data_download.py
    params:
      - config.yaml:
          - base
          - data_external.scvelo.pbmc68k
    outs:
      - ${data_external.scvelo.pbmc68k.rel_path}:
          persist: true

  data_download_larry:
    cmd: python data_download.py data_external.sources=[pyrovelocity] data_external.pyrovelocity.download=[larry]
    deps:
      - data_download.py
    params:
      - config.yaml:
          - base
          - data_external.pyrovelocity.larry
    outs:
      - ${data_external.pyrovelocity.larry.rel_path}:
          persist: true

  # preprocess:
  #   cmd: python preprocess.py
  #   deps:
  #     - preprocess.py
  #     - ${data_external.scvelo.pancreas.rel_path}
  #     - ${data_external.scvelo.pbmc68k.rel_path}
  #   params:
  #     - config.yaml:
  #         - base
  #         - data_external.scvelo.pancreas
  #         - data_external.scvelo.pbmc68k
  #   outs:
  #     - ${data_external.scvelo.pancreas.derived.rel_path}:
  #         persist: true
  #     - ${data_external.scvelo.pbmc68k.derived.rel_path}:
  #         persist: true

  preprocess_pancreas:
    cmd: python preprocess.py data_external.sources=[scvelo] data_external.scvelo.process=[pancreas]
    deps:
      - preprocess.py
      - ${data_external.scvelo.pancreas.rel_path}
    params:
      - config.yaml:
          - base
          - data_external.scvelo.pancreas
    outs:
      - ${data_external.scvelo.pancreas.derived.rel_path}:
          persist: true

  preprocess_pbmc68k:
    cmd: python preprocess.py data_external.sources=[scvelo] data_external.scvelo.process=[pbmc68k]
    deps:
      - preprocess.py
      - ${data_external.scvelo.pbmc68k.rel_path}
    params:
      - config.yaml:
          - base
          - data_external.scvelo.pbmc68k
    outs:
      - ${data_external.scvelo.pbmc68k.derived.rel_path}:
          persist: true

  train_pancreas_model1:
    cmd: python train.py model_training.train=[pancreas_model1]
    deps:
      - train.py
      - ${model_training.pancreas_model1.input_data_path}
    params:
      - config.yaml:
          - model_training.pancreas_model1
    metrics:
      - ${model_training.pancreas_model1.metrics_path}:
          cache: false
    outs:
      - ${model_training.pancreas_model1.run_info_path}:
          cache: false
      - ${model_training.pancreas_model1.training_parameters.loss_plot_path}
        # persist: true
      - ${model_training.pancreas_model1.trained_data_path}
        # persist: true
      - ${model_training.pancreas_model1.model_path}
        # persist: true
      - ${model_training.pancreas_model1.pyrovelocity_data_path}
        # persist: true

  train_pancreas_model2:
    cmd: python train.py model_training.train=[pancreas_model2]
    deps:
      - train.py
      - ${model_training.pancreas_model2.input_data_path}
    params:
      - config.yaml:
          - model_training.pancreas_model2
    metrics:
      - ${model_training.pancreas_model2.metrics_path}:
          cache: false
    outs:
      - ${model_training.pancreas_model2.run_info_path}:
          cache: false
      - ${model_training.pancreas_model2.training_parameters.loss_plot_path}
        # persist: true
      - ${model_training.pancreas_model2.trained_data_path}
        # persist: true
      - ${model_training.pancreas_model2.model_path}
        # persist: true
      - ${model_training.pancreas_model2.pyrovelocity_data_path}
        # persist: true

  plot_pancreas_model1:
    cmd: python fig2/fig2_pancreas_plot.py --config=config.yaml
    deps:
      - fig2/fig2_pancreas_plot.py
      - ${model_training.pancreas_model1.trained_data_path}
      - ${model_training.pancreas_model1.pyrovelocity_data_path}
    params:
      - config.yaml:
          - model_training.pancreas_model1
          - reports.figure2.pancreas_model1
    outs:
      - ${reports.figure2.pancreas_model1.shared_time_plot}
        # persist: true
      - ${reports.figure2.pancreas_model1.volcano_plot}
        # persist: true
      - ${reports.figure2.pancreas_model1.rainbow_plot}
        # persist: true
      - ${reports.figure2.pancreas_model1.vector_field_plot}
        # persist: true

  train_pbmc68k_model1:
    cmd: python train.py model_training.train=[pbmc68k_model1]
    deps:
      - train.py
      - ${model_training.pbmc68k_model1.input_data_path}
    params:
      - config.yaml:
          - model_training.pbmc68k_model1
    metrics:
      - ${model_training.pbmc68k_model1.metrics_path}:
          cache: false
    outs:
      - ${model_training.pbmc68k_model1.run_info_path}:
          cache: false
      - ${model_training.pbmc68k_model1.training_parameters.loss_plot_path}
        # persist: true
      - ${model_training.pbmc68k_model1.trained_data_path}
        #  persist: true
      - ${model_training.pbmc68k_model1.model_path}
        # persist: true
      - ${model_training.pbmc68k_model1.pyrovelocity_data_path}
        # persist: true

  train_pbmc68k_model2:
    cmd: python train.py model_training.train=[pbmc68k_model2]
    deps:
      - train.py
      - ${model_training.pbmc68k_model2.input_data_path}
    params:
      - config.yaml:
          - model_training.pbmc68k_model2
    metrics:
      - ${model_training.pbmc68k_model2.metrics_path}:
          cache: false
    outs:
      - ${model_training.pbmc68k_model2.run_info_path}:
          cache: false
      - ${model_training.pbmc68k_model2.training_parameters.loss_plot_path}
        # persist: true
      - ${model_training.pbmc68k_model2.trained_data_path}
        # persist: true
      - ${model_training.pbmc68k_model2.model_path}
        # persist: true
      - ${model_training.pbmc68k_model2.pyrovelocity_data_path}
        # persist: true

  figure2:
    cmd: python fig2/figure.py
    deps:
      - fig2/figure.py
      - ${model_training.pancreas_model1.trained_data_path}
      - ${model_training.pancreas_model1.pyrovelocity_data_path}
      - ${model_training.pbmc68k_model1.trained_data_path}
      - ${model_training.pbmc68k_model1.pyrovelocity_data_path}
    params:
      - config.yaml:
          - reports.figure2
    outs:
      - ${reports.figure2.tif_path}
        # persist: true
      - ${reports.figure2.svg_path}
        # persist: true
      - ${reports.figure2.biomarker_selection_path}
      - ${reports.figure2.biomarker_phaseportrait_path}

  figureS3:
    cmd: python figS3/figure.py
    deps:
      - figS3/figure.py
      - ${model_training.pancreas_model2.trained_data_path}
      - ${model_training.pancreas_model2.pyrovelocity_data_path}
      - ${model_training.pbmc68k_model2.trained_data_path}
      - ${model_training.pbmc68k_model2.pyrovelocity_data_path}
    params:
      - config.yaml:
          - reports.figureS3
    outs:
      - ${reports.figureS3.tif_path}
        # persist: true
      - ${reports.figureS3.svg_path}
        # persist: true
