name: pyro_latest
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - pyro-ppl=1.8.1
  - seaborn=0.11.2
  - scvelo=0.2.4
  - scvi-tools=0.13.0
  - pytorch-lightning=1.3.0
  - pytorch>=1.11.*
  - scikit-misc=0.1.4
  - torchmetrics=0.5.1
  - h5py=3.7.0
  - anndata=0.7.5
  - adjusttext=0.7.3
  - astropy=5.1
  - pip=22.2.2
  - pip:
      - graphviz
